# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Commit checks
on: pull_request

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7 # v1.3.0

  summary:
    runs-on: ubuntu-latest
    needs:
      - conventional-commits
    if: always()
    name: commit-check-summary
    steps:
      - name: Conventional commits summary
        run: if ${{ needs.conventional-commits.result != 'success' && needs.conventional-commits.result != 'skipped' }}; then exit 1; fi
